[package]
name = "fflazy"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Lazily-written bindings for FFmpeg"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.53.1"

[dependencies]

